### ISSUE TITLE
Should the header be binary onstead of JSON?

### ISSUE THREAD

**Issue by KOLANICH** [Narsil/safetensors#1]

**Comment by Narsil** [comment]
Hey @KOLANICH ,

Thanks for asking (sorry for not replying sooner, too many notifications these days).

It *could* be binary, but when doing the very rough spec, I thought it was not worth it.

Making it JSON means it's extra simple to parse the header from pretty much every language, whereas for binary, everyone would have to write the parse.

That means if we need to ways to read those file, only the indexing needs to be done basically.

This seems to become interesting again so we moved this repo back into the HF organisation, and we'll take a deeper look at that experiment (this was only a showcase about how we could avoid pytorch pickle)

**Comment by KOLANICH** [comment]
>Making it JSON means it's extra simple to parse the header from pretty much every language, whereas for binary, everyone would have to write the parse.

One can utilize flatbuf or Kaitai Struct to make it easier, but binary structures are usually much easier to parse rather than text ones that are usually ambigious and so require grammars to be created and debugged, which is nightmare even for simple ones.

BTW, could you add a comparison to `numpy` `npy`? It also has JSON-based header followed by a flattened array.

**Comment by Narsil** [comment]
>  but binary structures are usually much easier to parse rather than text ones 

I guess your mileage may vary here and it depends where you come from.
I personnally strongly disagree with that statement just because you would need a human readable file (like .proto or spec https://google.github.io/flatbuffers/flatbuffers_guide_writing_schema.html) to create the parser in the first place. Also they mostly are hard to maintain and evolve (in my experience at least, I know all frameworks claim it's simple, but I found tricky places more often than not).
AFAIK json parsing is implemented in all languages and is quite ubiquitous and human readable (this is important too). Binary parsers are always full of faults, and are much harder to evolve (in my experience at least).

Also this is a metadata header, which is orders of magnitude smaller than the following tensors (in most uses cases in ML), so performance overhead really is negligible.

> BTW, could you add a comparison to numpy npy? It also has JSON-based header followed by a flattened array.

You mean this ?
https://numpy.org/doc/stable/reference/generated/numpy.save.html
Afaik this supports only single arrays so not sure if it belongs. It also uses `pickle` under the hood by default (which this tries to avoid)
Array of arrays would be possible but missing the name of the arrays which are important when loading tensors.
Also numpy doesn't support `bfloat16` ( I might need to add a column on that, as a lot of these don't support that format which is indeed quite specific but is becoming increasingly more important in ML community.)

**Comment by KOLANICH** [comment]
>It also uses pickle under the hood by default (which this tries to avoid)

`numpy.load` by default has `allow_pickle=False`.

>Afaik this supports only single arrays

Thanks for the info.

>Array of arrays would be possible but missing the name of the arrays which are important when loading tensors.

Starts feeling like hdf5. Thanks for the info.

**Comment by Narsil** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.save.html

I was reading this. Don't know how it decides to use pickle or not during saving.. 

> Starts feeling like hdf5. Thanks for the info.

100% agree, if you check out the README, I flat out acknowledge this: 

> Apparently now discouraged for TF/Keras. Seems like a great fit otherwise actually. Some classic user after free issues: https://www.cvedetails.com/vulnerability-list/vendor_id-15991/product_id-35054/Hdfgroup-Hdf5.html. On a very different level than pickle security wise. Also 210k lines of code vs ~400 lines for this lib currently. 

For the TF/Keras discouraging it, it's still unclear why (source here: https://www.tensorflow.org/guide/keras/save_and_serialize).
The amount of lines of code is still a bit daunting to me in hdf5.
Another really important point for ML is the lack of support for `bfloat16`.

https://github.com/tensorflow/tensorflow/issues/26759
https://stackoverflow.com/questions/56116628/how-to-use-tf-keras-with-bfloat16

All those seem really old, so I'm not sure how likely it is that h5 will receive support.
